grok_ad_test_001_apikey="xai-eJNXNAboQ36l6PdEHlXOv67jEMYR8L2tj1NVupyQ5l1SlSkB6hgsQfGmnjJLY7gMZHpsxr9Q5SVLJ91k"

grok_api_url="https://api.x.ai/v1"

deepseek_apikey="sk-c135402c068e4c3dbf65ef5990042abf"

deepseek_api_url="https://api.deepseek.com"



pandasai_apikey="PAI-0a126575-cc6d-46e7-abfc-7accba877a7a"